<?php

use App\Models\VRPagesTranslations;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PagesTranslationsSeeder extends Seeder
{
        /**
         * Run the database seeds.
         *
         * @return void
         */
        public function run()
    {
        $pagesTranslations = [
            ["page_id" => "apie", "language_id" => "lt", "title" => "Apie", "description_short" => "Virtuali realybė vis labiau skverbiasi į mūsų kasdienybę ir visas sritis nuo pramogų iki mokslo. todėl pristatome unikalią galimybę rytojų pamatyti jau dabar! Jaudinanti ir įtraukianti patirtis garantuota visiems.", "description_long" => "Virtuali realybė vis labiau skverbiasi į mūsų kasdienybę ir visas sritis nuo pramogų iki mokslo. todėl pristatome unikalią galimybę rytojų pamatyti jau dabar! Jaudinanti ir įtraukianti patirtis garantuota visiems - ir pirmą kartą išmėginsiantiems virtualią realybę, ir tiems, kurie jau žino kas tai yra. 10 skirtingų patirčių ir net 60 minučių įspūdžių, adrenalino ir atradimų laukia kiekvieno apsilankiusiojo. Paruošėme trijų skirtingų sudėtingumo lygių patirtis - nuo irklavimo Galvės ežere ar leidimosi parašiutu iki Mini golfo žaidimo ant pilies sienų ar stebuklingo gėrimo gamybos. Tačiau neabejojame, jog norėsi išbandyti visas. Virtuali realybė suteikia progą pažvelgti į pasaulį kitomis akimis ir iš paprasto stebėtojo virsti veiksmo dalyviu. Aukštos kokybės grafika, realūs vaizdai ir galimybė interaktyviai dalyvauti patirtyje tiesiog įtraukia! Tad ateik, užsidėk VR akinius ir atsidurk kitame pasaulyje, kur pojūčiai yra visai ne virtualūs! Pasiimk ir draugą, kad palaikytų už rankos, nes įspūdžių netrūks.", "slug" => "apie"],
            ["page_id" => "about", "language_id" => "en", "title" => "About", "description_short" => "Virtuali realybė vis labiau skverbiasi į mūsų kasdienybę ir visas sritis nuo pramogų iki mokslo. todėl pristatome unikalią galimybę rytojų pamatyti jau dabar! Jaudinanti ir įtraukianti patirtis garantuota visiems.", "description_long" => "Virtuali realybė vis labiau skverbiasi į mūsų kasdienybę ir visas sritis nuo pramogų iki mokslo. todėl pristatome unikalią galimybę rytojų pamatyti jau dabar! Jaudinanti ir įtraukianti patirtis garantuota visiems - ir pirmą kartą išmėginsiantiems virtualią realybę, ir tiems, kurie jau žino kas tai yra. 10 skirtingų patirčių ir net 60 minučių įspūdžių, adrenalino ir atradimų laukia kiekvieno apsilankiusiojo. Paruošėme trijų skirtingų sudėtingumo lygių patirtis - nuo irklavimo Galvės ežere ar leidimosi parašiutu iki Mini golfo žaidimo ant pilies sienų ar stebuklingo gėrimo gamybos. Tačiau neabejojame, jog norėsi išbandyti visas. Virtuali realybė suteikia progą pažvelgti į pasaulį kitomis akimis ir iš paprasto stebėtojo virsti veiksmo dalyviu. Aukštos kokybės grafika, realūs vaizdai ir galimybė interaktyviai dalyvauti patirtyje tiesiog įtraukia! Tad ateik, užsidėk VR akinius ir atsidurk kitame pasaulyje, kur pojūčiai yra visai ne virtualūs! Pasiimk ir draugą, kad palaikytų už rankos, nes įspūdžių netrūks.", "slug" => "about"],
            ["page_id" => "O_проекте", "language_id" => "ru", "title" => "O проекте", "description_short" => "Virtuali realybė vis labiau skverbiasi į mūsų kasdienybę ir visas sritis nuo pramogų iki mokslo. todėl pristatome unikalią galimybę rytojų pamatyti jau dabar! Jaudinanti ir įtraukianti patirtis garantuota visiems.", "description_long" => "Virtuali realybė vis labiau skverbiasi į mūsų kasdienybę ir visas sritis nuo pramogų iki mokslo. todėl pristatome unikalią galimybę rytojų pamatyti jau dabar! Jaudinanti ir įtraukianti patirtis garantuota visiems - ir pirmą kartą išmėginsiantiems virtualią realybę, ir tiems, kurie jau žino kas tai yra. 10 skirtingų patirčių ir net 60 minučių įspūdžių, adrenalino ir atradimų laukia kiekvieno apsilankiusiojo. Paruošėme trijų skirtingų sudėtingumo lygių patirtis - nuo irklavimo Galvės ežere ar leidimosi parašiutu iki Mini golfo žaidimo ant pilies sienų ar stebuklingo gėrimo gamybos. Tačiau neabejojame, jog norėsi išbandyti visas. Virtuali realybė suteikia progą pažvelgti į pasaulį kitomis akimis ir iš paprasto stebėtojo virsti veiksmo dalyviu. Aukštos kokybės grafika, realūs vaizdai ir galimybė interaktyviai dalyvauti patirtyje tiesiog įtraukia! Tad ateik, užsidėk VR akinius ir atsidurk kitame pasaulyje, kur pojūčiai yra visai ne virtualūs! Pasiimk ir draugą, kad palaikytų už rankos, nes įspūdžių netrūks.", "slug" => "O_проекте"],
            ["page_id" => "kontaktai", "language_id" => "lt", "title" => "Kontaktai", "description_short" => "Paroda veiks nuo kovo mėn. 1 d. iki gegužės mėn. 31 d., Darbo laikas: darbo dienomis nuo 11 val. iki 22 val., savaitgaliais nuo 10 val. iki 22 val. Paroda vyksta, Vilniuje PC 'Akropolis', 2-ame aukšte, prie knygyno 'Pegasas'.", "description_long" => "Paroda veiks nuo kovo mėn. 1 d. iki gegužės mėn. 31 d., Darbo laikas: darbo dienomis nuo 11 val. iki 22 val., savaitgaliais nuo 10 val. iki 22 val. Paroda vyksta, Vilniuje PC 'Akropolis', 2-ame aukšte, prie knygyno 'Pegasas'. Bilietus galite įsigyti parodos kasoje.", "slug" => "kontaktai"],
            ["page_id" => "contact", "language_id" => "en", "title" => "Contact", "description_short" => "Paroda veiks nuo kovo mėn. 1 d. iki gegužės mėn. 31 d., Darbo laikas: darbo dienomis nuo 11 val. iki 22 val., savaitgaliais nuo 10 val. iki 22 val. Paroda vyksta, Vilniuje PC 'Akropolis', 2-ame aukšte, prie knygyno 'Pegasas'.", "description_long" => "Paroda veiks nuo kovo mėn. 1 d. iki gegužės mėn. 31 d., Darbo laikas: darbo dienomis nuo 11 val. iki 22 val., savaitgaliais nuo 10 val. iki 22 val. Paroda vyksta, Vilniuje PC 'Akropolis', 2-ame aukšte, prie knygyno 'Pegasas'. Bilietus galite įsigyti parodos kasoje.", "slug" => "contact"],
            ["page_id" => "Kонтакты", "language_id" => "ru", "title" => "Kонтакты", "description_short" => "Paroda veiks nuo kovo mėn. 1 d. iki gegužės mėn. 31 d., Darbo laikas: darbo dienomis nuo 11 val. iki 22 val., savaitgaliais nuo 10 val. iki 22 val. Paroda vyksta, Vilniuje PC 'Akropolis', 2-ame aukšte, prie knygyno 'Pegasas'.", "description_long" => "Paroda veiks nuo kovo mėn. 1 d. iki gegužės mėn. 31 d., Darbo laikas: darbo dienomis nuo 11 val. iki 22 val., savaitgaliais nuo 10 val. iki 22 val. Paroda vyksta, Vilniuje PC 'Akropolis', 2-ame aukšte, prie knygyno 'Pegasas'. Bilietus galite įsigyti parodos kasoje.", "slug" => "Kонтакты"],
            ["page_id" => "the_lab_lt", "language_id" => "lt", "title" => "The Lab", "description_short" => "Tavo pilį puolą žvėriški barbarai, o tu turi tik lanką, kad juos sustabdytum. Tačiau tai viskas ko reikia tokiam patyrusiam kariui kaip tu - apsaugok savo pilį nuo priešų.", "description_long" => "Tavo pilį puolą žvėriški barbarai, o tu turi tik lanką, kad juos sustabdytum. Tačiau tai viskas ko reikia tokiam patyrusiam kariui kaip tu - apsaugok savo pilį nuo priešų.", "slug" => "the_lab_lt"],
            ["page_id" => "the_lab_en", "language_id" => "en", "title" => "The Lab", "description_short" => "Tavo pilį puolą žvėriški barbarai, o tu turi tik lanką, kad juos sustabdytum. Tačiau tai viskas ko reikia tokiam patyrusiam kariui kaip tu - apsaugok savo pilį nuo priešų.", "description_long" => "Tavo pilį puolą žvėriški barbarai, o tu turi tik lanką, kad juos sustabdytum. Tačiau tai viskas ko reikia tokiam patyrusiam kariui kaip tu - apsaugok savo pilį nuo priešų.", "slug" => "the_lab_en"],
            ["page_id" => "the_lab_ru", "language_id" => "ru", "title" => "The Lab", "description_short" => "Tavo pilį puolą žvėriški barbarai, o tu turi tik lanką, kad juos sustabdytum. Tačiau tai viskas ko reikia tokiam patyrusiam kariui kaip tu - apsaugok savo pilį nuo priešų.", "description_long" => "Tavo pilį puolą žvėriški barbarai, o tu turi tik lanką, kad juos sustabdytum. Tačiau tai viskas ko reikia tokiam patyrusiam kariui kaip tu - apsaugok savo pilį nuo priešų.", "slug" => "the_lab_ru"],
            ["page_id" => "fruit_ninja_lt", "language_id" => "lt", "title" => "Fruit Ninja", "description_short" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "description_long" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "slug" => "fruit_ninja_lt"],
            ["page_id" => "fruit_ninja_en", "language_id" => "en", "title" => "Fruit Ninja", "description_short" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "description_long" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "slug" => "fruit_ninja_en"],
            ["page_id" => "fruit_ninja_ru", "language_id" => "ru", "title" => "Fruit Ninja", "description_short" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "description_long" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "slug" => "fruit_ninja_ru"],
            ["page_id" => "space_pirate_trainer_lt", "language_id" => "lt", "title" => "Space Pirate Trainer", "description_short" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "description_long" => "Tai puiki proga išpildyti vaikystės svajonę būti kosmoso piratu. Čia išmoksi visko, ko tau reikės. Paimk skydą, nutaikyk ginklą ir pirmyn!", "slug" => "space_pirate_trainer_lt"],
            ["page_id" => "space_pirate_trainer_en", "language_id" => "en", "title" => "Space Pirate Trainer", "description_short" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "description_long" => "Tai puiki proga išpildyti vaikystės svajonę būti kosmoso piratu. Čia išmoksi visko, ko tau reikės. Paimk skydą, nutaikyk ginklą ir pirmyn!", "slug" => "space_pirate_trainer_en"],
            ["page_id" => "space_pirate_trainer_ru", "language_id" => "ru", "title" => "Space Pirate Trainer", "description_short" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "description_long" => "Tai puiki proga išpildyti vaikystės svajonę būti kosmoso piratu. Čia išmoksi visko, ko tau reikės. Paimk skydą, nutaikyk ginklą ir pirmyn!", "slug" => "space_pirate_trainer_ru"],
            ];

        DB::beginTransaction ();
        try {
            foreach ($pagesTranslations as $pageData) {
                $role = VRPagesTranslations::where ('slug', $pageData['slug'])->first ();
                if (!$role)
                    VRPagesTranslations::create ($pageData);
            }
        } catch (\Exception $e) {
            DB::rollback ();
            throw new Exception($e->getMessage ());
        }
        DB::commit ();
    }

}
